# og tree is the tree with the 3 mill variants, all chromosomes and genomic offset (no overlapping pos)
og_vcf_offset: 'data/wholegenome_offset.vcf'
og_tree_offset: 'data/og_tree_offset.trees'
#allele_freq_params: 'data/allele_freq_params.csv'
heritability_params: 'data/heritability_params.csv'
polygenicity_params: 'data/polygenicity_params.csv'

mapper_realid_metadataid: 'data/mapper_realid_metadataid_wholegenomeoffset.csv'
pos_vcf_og: 'data/pos_vcf_og_nooffset.csv'
pos_vcf_og_offset: 'data/pos_vcf_og_offset.csv'
allele_freq_founder_offset: 'data/allele_freq_founder_offset.csv'
pc_founders: 'data/pc_founders'

## gwas
fam_file: 'data/greneNet_final_v1.1.recode.fam'
bed_file: 'data/greneNet_final_v1.1.recode.bed'
bim_file: 'data/greneNet_final_v1.1.recode.bim'
kinship: 'data/output/greneNet_final_v1.1.recode.cXX.txt'

ecotypes_grenenet: 'data/ecotypes_grenenet.csv'
nonhet_pos: 'data/nonhet_pos_wholegenome_offset.csv'

heritability: ['1','3','4','5'] # partial 
#heritability: ['1','2','3','4','5'] # full 

#allele_freq: ['2','4','6'] # partial 
#allele_freq: ['1','2','3','4','5','6'] # full

# proportion of contributin snps to the trait
# pi: ['1','2','3','4','5','6','7'] # partial 
pi: ['1','2','5','10','20','50','100','500','1000'] # full

# standard deviation of effect sizÍes of contributing loci 
# beta: ['beta']

## this si standard deviation which makes de variance 1 and 4 
beta: 2

# variances to simulate different strength of selection 
selection: ['estrongsel']
# ['estrongsel','exstrongsel', 'strongsel', 'moderatesel']
#'exstrongsel',
# 'estrongsel', 

# 'strongsel', 
exstrongsel: 0.001
estrongsel: 0.01
vstrongsel: 0.05
strongsel: 0.1
strongmod: 0.5
moderatesel: 1
lowsel: 3

# number of replicates of each simulation to run
replicates_sim: [1,2,3,4,5]
replicates_arq: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]

# number of different environments to simulate
#optima: [-4,-3,-2,-1,0,1,2,3,4]
optima: [1]  # 0,1,1.5,2,3,4,5,6
#mapenv: '{-5:0, -4:1, -3:2, -2:3, -1:4, 0:5, 1:6, 2:7, 3:8 , 4:9 ,5:10}'


### for gwas
# base fasta file used by slim 
# base_fasta: 'data/chr5.fasta'
# base_fam: 'data/chr5_grenenet.fam'

# bed_file: 'data/chr5_grenenet.bed'
# bim_file: 'data/chr5_grenenet.bim'
# kinship: 'data/chr5_grenenet_kinship.cXX.txt'

## ld pruning settings
# maf: 0.6
# corr_ld: 0.01
