__default__:
  time: 1200 # Default time (minutes). A time limit of zero requests that no time limit be impo
  mem: 60G # Default memory. A memory size specification of zero grants the job access to all of the memory on each node.
  cpus-per-task: 10
  nodes: 1
  ntasks: 1

rule run_lmm_nopc:
    threads: 20
    time: 2880
