# og tree is the tree with the 3 mill variants, all chromosomes and genomic offset (no overlapping pos)
og_vcf_offset: 'data/wholegenome_offset.vcf'
og_tree_offset: 'data/og_tree_offset.trees'
mapper_realid_metadataid: 'data/mapper_realid_metadataid_wholegenomeoffset.csv'
pos_vcf_og: 'data/pos_vcf_og.csv'

allele_freq: ['lowfreq',
              'mediumfreq',
              'highfreq']

lowfreq: [0, 0.05]
mediumfreq: [0.05, 0.5]
highfreq: [0.5, 1]

# proportion of contributin snps to the trait
pi: ['monogen','fivepoly', 'twentypoly', 'onehpoly']

monogen: 1
fivepoly: 5
twentypoly: 20
onehpoly: 100

# standard deviation of effect sizÍes of contributing loci 
beta: ['lowbeta', 'highbeta']

## this si standard deviation which makes de variance 1 and 4 
lowbeta: 1
highbeta: 2

# variances to simulate different strength of selection 
selection: ['strongsel', 'moderatesel', 'lowsel']

strongsel: 1
moderatesel: 3
lowsel: 5

# number of replicates of each simulation to run
replicates: 5
# number of different environments to simulate
optima_qty: 5




### for gwas
# base fasta file used by slim 
# base_fasta: 'data/chr5.fasta'
# base_fam: 'data/chr5_grenenet.fam'

# bed_file: 'data/chr5_grenenet.bed'
# bim_file: 'data/chr5_grenenet.bim'
# kinship: 'data/chr5_grenenet_kinship.cXX.txt'

## ld pruning settings
# maf: 0.6
# corr_ld: 0.01
